// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhobwjgpbgxfpxtblhgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ob2J3amdwYmd4ZnB4dGJsaGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzc4NTIsImV4cCI6MjA2OTgxMzg1Mn0.xuMx0mNz173VeKYBFmnfBkFQ2Lxe6H9l-RjHlbb70Es";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});